# Generated by Django 3.2.6 on 2021-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID_Product', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=500)),
                ('Product_price', models.IntegerField()),
                ('Product_image', models.ImageField(blank=True, upload_to='TikTak/static/img/')),
                ('Product_color', models.CharField(max_length=20)),
                ('Product_brand', models.CharField(max_length=100)),
                ('Product_size', models.CharField(default='S M L XL', max_length=30)),
                ('Product_characteristics', models.CharField(max_length=1000)),
                ('Product_Category', models.CharField(choices=[('Шортики', 'Shorts'), ('Платье', 'Dress'), ('Пеленки', 'Deaper'), ('Носки', 'Socks'), ('Майки', 'T-Shirts'), ('Обувь', 'shoes')], default='Шортики', max_length=7)),
                ('for_which_gender', models.CharField(choices=[('Для мальчиков', 'Мальчиков'), ('Для девочек', 'Девочек')], default=None, max_length=15)),
            ],
        ),
    ]
