# Generated by Django 3.2.6 on 2021-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(max_length=450, upload_to='TikTak/static/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.CharField(choices=[('Shorts', 'Шортики'), ('Dress', 'Платье'), ('Deaper', 'Пеленки'), ('Socks', 'Носки'), ('T-Shirts', 'Майки'), ('shoes', 'Обувь')], default='None', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_which_gender',
            field=models.CharField(choices=[('Boys', 'Для мальчиков'), ('Girls', 'Для девочек')], default=None, max_length=15),
        ),
    ]
