# Generated by Django 3.2.6 on 2021-09-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_brand',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_size',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_which_gender',
            field=models.CharField(choices=[('Для мальчиков', 'Boys'), ('Для девочек', 'Girls')], default=None, max_length=15),
        ),
    ]
