# Generated by Django 3.2.6 on 2021-10-05 13:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0002_auto_20210929_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('от 0 - 2-х мес', '0-2'), ('от двух до трех мес.', '2-3'), ('от трех до пяти мес.', '3-5'), ('от шести до восьми мес.', '6-8'), ('от девяти мес. до одного года', '9-1')], max_length=110),
        ),
    ]
