# Generated by Django 3.2.6 on 2022-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0002_auto_20211225_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
