# Generated by Django 3.2.6 on 2021-10-07 23:45

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0003_alter_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.CharField(choices=[('Шортики', 'Shorts'), ('Платье', 'Dress'), ('Пеленки', 'Deaper'), ('Носки', 'Socks'), ('Майки', 'T-Shirts'), ('Обувь', 'shoes')], default='None', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0-3 месяца', '0-3'), ('3-6 месяцев', '3-6'), ('6-12 месяцев', '6-12'), ('12-18 месяцев', '12-18'), ('18-24 месяца', '18-24'), ('2 года', '2-y'), ('3 года', '3-y'), ('4 года', '4-y'), ('5 лет', '5-y'), ('6 лет', '6-y'), ('7 лет', '7-y'), ('8 лет', '8-y'), ('9 лет', '9-y'), ('10 лет', '10-y'), ('11 лет', '11-y'), ('12 лет', '12-y'), ('13 лет', '13-y'), ('14 лет (XS)', '14-y'), ('16 лет (S)', '16-y'), ('18 лет (M)', '18-y')], max_length=175),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TikTak/static/img/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TikTak.product')),
            ],
        ),
    ]
