# Generated by Django 3.2.6 on 2022-03-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0004_alter_imagegallery_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField()),
                ('when_set_discount_time', models.DateTimeField(auto_now=True)),
                ('when_discount_time_out', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='TikTak.product')),
            ],
        ),
    ]
