# Generated by Django 3.2.6 on 2021-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0004_auto_20211008_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='Product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_image',
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='TikTak/static/img'),
        ),
    ]
