# Generated by Django 3.2.6 on 2021-10-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0005_auto_20211008_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
