# Generated by Django 3.2.6 on 2021-10-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0006_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Added_time',
            field=models.DateField(auto_now=True),
        ),
    ]
