# Generated by Django 3.2.6 on 2021-10-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikTak', '0007_product_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
