# Generated by Django 3.2.8 on 2021-10-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='objects_id',
            new_name='object_id',
        ),
    ]
